FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
ARG GITVERSION
WORKDIR /app
ARG GITVERSION
ARG PLUGINVERSION
ARG PLUGIN2VERSION
ARG PLUGIN3VERSION
ARG PLUGIN4VERSION
ARG PLUGIN5VERSION

# Copy csproj and restore as distinct layers
COPY eform-debian-service ./eform-debian-service
COPY eform-service-items-planning-plugin ./eform-service-items-planning-plugin
COPY eform-service-workflow-plugin ./eform-service-workflow-plugin
COPY eform-service-timeplanning-plugin ./eform-service-timeplanning-plugin
COPY eform-service-backendconfiguration-plugin ./eform-service-backendconfiguration-plugin
RUN dotnet publish -o out /p:Version=$GITVERSION --runtime linux-x64 --configuration Release eform-debian-service
RUN dotnet publish -o out/Plugins/ServiceItemsPlanningPlugin /p:Version=$PLUGINVERSION --runtime linux-x64 --configuration Release eform-service-items-planning-plugin
RUN dotnet publish -o out/Plugins/ServiceWorkflowPlugin /p:Version=$PLUGIN3VERSION --runtime linux-x64 --configuration Release eform-service-workflow-plugin
RUN dotnet publish -o out/Plugins/ServiceTimePlanningPlugin /p:Version=$PLUGIN4VERSION --runtime linux-x64 --configuration Release eform-service-timeplanning-plugin
RUN dotnet publish -o out/Plugins/ServiceBackendConfigurationPlugin /p:Version=$PLUGIN5VERSION --runtime linux-x64 --configuration Release eform-service-backendconfiguration-plugin
RUN pwd
RUN ls -lah out
RUN ls -lah out/Plugins

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .

ENV DEBIAN_FRONTEND noninteractive
ENV Logging__Console__FormatterName=

RUN mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1
RUN apt-get update && \
	apt-get -y -q install \
		libxml2 \
		libgdiplus \
		libc6-dev \
		libreoffice \
		libreoffice-writer \
		ure \
		libreoffice-java-common \
		libreoffice-core \
		libreoffice-common \
		fonts-opensymbol \
		hyphen-fr \
		hyphen-de \
		hyphen-en-us \
		hyphen-it \
		hyphen-ru \
		fonts-dejavu \
		fonts-dejavu-core \
		fonts-dejavu-extra \
		fonts-droid-fallback \
		fonts-dustin \
		fonts-f500 \
		fonts-fanwood \
		fonts-freefont-ttf \
		fonts-liberation \
		fonts-lmodern \
		fonts-lyx \
		fonts-sil-gentium \
		fonts-texgyre \
		fonts-tlwg-purisa \
		htop && \
	apt-get -y -q remove libreoffice-gnome && \
	apt -y autoremove && \
	rm -rf /var/lib/apt/lists/*

RUN adduser --home=/opt/libreoffice --disabled-password --gecos "" --shell=/bin/bash libreoffice

ENTRYPOINT ["dotnet", "MicrotingService.dll"]
