apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "angularfrontend.fullname" . }}
  labels:
    {{- include "angularfrontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "angularfrontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "angularfrontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "angularfrontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 15
            tcpSocket:
              port: 5000
          readinessProbe:
            failureThreshold: 20
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            tcpSocket:
              port: 5000
          resources:
            limits:
              memory: "612Mi"
            requests:
              memory: "356Mi"
              cpu: "150m"
          args:
            [
            "/ConnectionString=Persist Security Info=True;host={{ include "angularfrontend.databaseHost" . }};Database={{ regexReplaceAll "frontend-(x*)" .Release.Name "$1" }}_Angular;user = root; password = secretpassword;port=3306;Convert Zero Datetime = true;SslMode=none;",
            "/Token=df",
            "/Password=abc123456"

            ]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - s-2vcpu-4gb
              - key: node.kubernetes.io/instance-type
                operator: NotIn
                values:
                - s-2vcpu-4gb-amd
              - key: node.kubernetes.io/instance-type
                operator: NotIn
                values:
                - s-1vcpu-2gb
