apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debian-service.fullname" . }}
  labels:
    {{- include "debian-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "debian-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "debian-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "debian-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
              cpu: "100m"
          args:
            [
            "/ConnectionString=host={{ .Release.Name }}-mariadb;Database={{ regexReplaceAll "frontend-(x*)" .Release.Name "$1" }}_SDK;user = root; password = secretpassword;port=3306;Convert Zero Datetime = true;SslMode=none;",
            "/RabbitmqHost={{ .Release.Name }}-rabbitmq",
            "/Password=abc123456"

            ]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - s-2vcpu-4gb
              - key: node.kubernetes.io/instance-type
                operator: NotIn
                values:
                - s-2vcpu-4gb-amd
              - key: node.kubernetes.io/instance-type
                operator: NotIn
                values:
                - s-1vcpu-2gb
